### ISSUE TITLE
DOI collection meta-analyses

### ISSUE THREAD

**Issue by chartgerink** [chartgerink/2017oa-ma#1]
- [x] [10.1037/a0031859](https://doi.org/10.1037/a0031859)
- [ ] [10.1037/a0037737](https://doi.org/10.1037/a0037737)
- [ ] [10.1037/a0035661](https://doi.org/10.1037/a0035661)
- [ ] [10.1037/a0032432](https://doi.org/10.1037/a0032432)
- [ ] [10.1037/a0033890](https://doi.org/10.1037/a0033890)
- [ ] [10.1037/a0035740](https://doi.org/10.1037/a0035740)
- [ ] [10.1037/a0037428](https://doi.org/10.1037/a0037428)
- [ ] [10.1037/a0033065](https://doi.org/10.1037/a0033065)
- [ ] [10.1037/a0035236](https://doi.org/10.1037/a0035236)
